#!/bin/bash

function gps_check {
	export USBFORRF=/dev/ttyUSB$(dmesg | grep cp210x | tail -1 |  sed -e 's/\(^.*\)\(.$\)/\2/')
	export USBFORGPS=/dev/ttyUSB$(dmesg | grep pl2303 | tail -1 |  sed -e 's/\(^.*\)\(.$\)/\2/')

	#Determine the USB belonging
	echo "# Default settings for gpsd." >/etc/default/gpsd
	echo "# Please do not edit this file directly - use \`dpkg-reconfigure gpsd\' to" >>/etc/default/gpsd
	echo "# change the options." >>/etc/default/gpsd
	echo "START_DAEMON=\"true\"" >>/etc/default/gpsd
	echo "GPSD_OPTIONS=\"\"" >>/etc/default/gpsd
	echo "DEVICES=\"$USBFORGPS\"" >>/etc/default/gpsd
	echo "USBAUTO=\"false\"" >>/etc/default/gpsd
	echo "GPSD_SOCKET=\"/var/run/gpsd.sock\"" >>/etc/default/gpsd
}


function RF_check {
	export USBFORRF=$(dmesg | grep cp210x | tail -1 |  sed -e 's/\(^.*\)\(.$\)/\2/')

	while [[ $USBFORRF != "1" && $USBFORRF != "0" && $USBFORRF != "2" ]]
	do
	export USBFORRF=$(dmesg | grep cp210x | tail -1 |  sed -e 's/\(^.*\)\(.$\)/\2/')
	timeout 4 aplay $TVWSPATH/connectSS.wav -q
	echo "Reconnect the RF..."
	done 

	USBFORRF=/dev/ttyUSB$(dmesg | grep cp210x | tail -1 |  sed -e 's/\(^.*\)\(.$\)/\2/')
	echo "RF connected!"
}


/etc/init.d/gpsd restart

USBFORRF=/dev/ttyUSB$(dmesg | grep cp210x | tail -1 |  sed -e 's/\(^.*\)\(.$\)/\2/')

#program directory
TVWSPATH=/home/pi/TVWS

#Minimum number of packets to get a TPV record
RECORDS=4
#Maximum number of packets to get a TPV record (depends on the Android APP)
#ex: BT2GPS needed MAX=11 and after v4 needs MAX=15
MAXRECORDS=15


#Look for the lastest registered file
if [ "$(ls -A $TVWSPATH/data/complete)" ]; then
	latest_file=$(ls -tr $TVWSPATH/data/complete | sort -n | tail -n 1)
	echo "Latest measure"
	echo $latest_file
	count=$(echo ${latest_file%.*})
else
	echo "$TVWSPATH/data/400 is Empty"
	count=1
fi

RF_check

while :
do

	echo "RECORDS: $RECORDS"

	# Added a timeout of 15 secs because from time to time the pipe to gpsd hangs.
	# So gpsd has to be reset
	# The previous solution was to reset the bluetooth conection at the phone

	ACTIVATED=$(timeout 8 "gpspipe" "-w" "-n" "3" | grep activated)

	if [ "$ACTIVATED" ]; then
	TPV=$(timeout 5 "gpspipe" "-w" "-n" "$RECORDS")
	   if [ "$TPV" ]; then
	      TPV=$(echo $TPV | grep -m 1 TPV)
	   else
	      echo "gpspipe is timing out!"
	   fi
	else
		TPV=""
		gps_check
		RF_check
		timeout 4 aplay "$TVWSPATH/nogps.wav" "-q"
		echo "GPS deamon not ACTIVATED: waiting for the gpsd to wakeup"
		sudo /etc/init.d/gpsd restart
	fi

	echo $TPV

	latitude=$(echo $TPV | sed -e 's/[{}]/''/g' | awk -v RS=',"' -F: '/^lat/ {print $2}')
	longitude=$(echo $TPV | sed -e 's/[{}]/''/g' | awk -v RS=',"' -F: '/^lon/ {print $2}')


	# After it was missing longitud line to execute on 20/5/13
	# I had to add an extra checking.

	if [ -z "$latitude" ] || [ -z "$longitude" ]
	then
		echo "Missing Lat or Lon, please check the code!"
	fi


	# Measure spectrum // OJO
	if [ ! -z "$latitude" ] && [ ! -z "$longitude" ]
		then
		timeout .5 aplay $TVWSPATH/beep-8.wav -q
	if [ "$RECORDS" -gt 4 ]; then 
		RECORDS=`expr $RECORDS - 1`  #Exit status 
									 # 0 if EXPRESSION is neither null nor 0,
									 # 1 if EXPRESSION is null or 0,
									 # 2 if EXPRESSION is syntactically invalid, 
									 # 3 if an error occurred. 
	fi

	echo "MEASUMENT NUMBER: $count"

	dmeas=$(date)
	echo $dmeas
	echo "LATITUDE"
	echo $latitude
	echo "LONGITUDE"
	echo $longitude


	cd $TVWSPATH/data/complete
	RFE=$(timeout 10 /home/pi/TVWS/rfexplorer $USBFORRF 0300000 0900000 040 120 $count.txt >$count.txt)

	if [[ $RFE -eq "0" ]]; then
		FILESIZE=$(stat -c%s "$count.txt")
		if [[ $FILESIZE < 1800 ]]; then
			echo "problem with RF, unplug and plug it again".
			RF_check
		fi

		echo $latitude >> $TVWSPATH/data/complete/$count.txt
		echo $longitude >> $TVWSPATH/data/complete/$count.txt
		echo $dmeas >> $TVWSPATH/data/complete/$count.txt

		count=`expr $count + 1`
		else
			aplay $TVWSPATH/telephone-ring-3.wav -q
		fi
	else
		 if [ "$RECORDS" -lt $MAXRECORDS ]; then
		 RECORDS=`expr $RECORDS + 1`
		else
		 RECORDS=10
		 gps_check
		 timeout 4 aplay "$TVWSPATH/nogps.wav" "-q"
		 echo "GPS deamon not ACTIVATED: waiting for the gpsd to wakeup"
		 sudo /etc/init.d/gpsd restart
		fi
	fi

done
